account/urls.py
from django.urls import path

from .import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('verify/<auth_token>', views.verify, name='verify'),
    path('login/', views.login_, name='login'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
    path('change/<token>', views.change, name='change'),
    path('logout/', views.out, name='logout'),
    path('doimatkhau/', views.doimatkhau, name='doimatkhau')
]

chatapp/urls.py
from django.urls import path
from .import views
app_name = 'chatapp'
urlpatterns = [
    path('getMessages/<int:id>/', views.getMessages, name='getMessages'),
    path('', views.home, name='home'),
    path('message/<int:id>', views.messa, name='message'),
    path('send/', views.send, name='send'),
]

core/urls.py
from django.urls import path
from .import views

app_name = 'core'


urlpatterns = [
    path('product/<int:id>/', views.oneproduct, name='oneproduct'),
    path('', views.index, name='index'),
    path('product/<slug:slug>/', views.ViewCategory, name='viewcategory'),
    path('search/', views.serach, name='search'),
    path('cart/', views.cart__, name='cart'),
    path('addorderitem/', views.addorderitem, name='addorderitem'),
    path('edit/<int:id>/', views.edititem, name='edit'),
    path('checkout/', views.checkout, name='checkout'),
    path('pending/', views.pending, name='pending'),
    path('profile/', views.profile, name='profile'),
    path('commet/', views.comment_, name='commet'),
    path('contact/', views.contact, name='contact'),
    path('updateprofile/', views.updateprofile, name='updateprofile')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('account.urls')),
    path('chat/', include('chatapp.urls')),
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from product.models import Product



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_order = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=200,null=True)

    def __str__(self) -> str:
        return str(self.user.username)
    
    @property
    def total_items_price(self):
        total=0
        orderitem = self.ortheritem_set.all()
        for i in orderitem:
            total += i.total_price
        return total
    @property
    def total_item(self):
        total=0
        orderitem = self.ortheritem_set.all()
        for i in orderitem:
            total += i.quantity
        return total

class OrtherItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.product.name)
    
    @property
    def total_price(self):
        total = int(self.quantity)*int(self.product.price)
        return total

core/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User
from category.models import Category
# Create your models here.



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.FloatField()
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    hasbeensell = models.IntegerField(default=0,blank=True, null=True)
    evaluate = models.FloatField(null=True, blank=True, default=0)
    create_at = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return str(self.name)
    
    
    @property
    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url =''
        return url
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    product =  models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.TextField()
    star = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

cart/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render, HttpResponse, redirect
from category.models import Category
from product.models import Product, Comment
from cart.models import Cart, OrtherItem
from shippingaddress.models import ShippingAddress, PurchaseHistory
from django.shortcuts import get_object_or_404
from django.db.models import Q
from account.models import customeruser


def index(request):
    if request.method=="GET":
        user = request.user
        categorys = Category.objects.all()
        if request.user.is_authenticated:
            cart_ = Cart.objects.get(user = user)
            orderitems = OrtherItem.objects.filter(cart = cart_)
            count = orderitems.count()
            return render(request, 'core/home.html',{'categorys':categorys,'user':user,'count':count})
        else:
            count = 0
            return render(request, 'core/home.html',{'categorys':categorys,'user':user,'count':count})
    else:
        return redirect('core:index')



def ViewCategory(request, slug):
    if request.method == "GET":
        categorys = Category.objects.all()
        obj = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(category = obj)
        if request.user.is_authenticated:
            user = request.user
            cart_ = Cart.objects.get(user = user)
            orderitems = OrtherItem.objects.filter(cart = cart_)
            count = orderitems.count()
            return render(request, 'core/product.html',{'products':products,'categorys':categorys,'obj':obj,'count':count})
        else:
            count = 0
            return render(request, 'core/product.html',{'products':products,'categorys':categorys,'obj':obj,'count':count})
    else:
        return redirect('core:index')


# serach product

def serach(request):
    if request.method == "GET":
        q = request.GET.get('q')
        if q :
            products = Product.objects.filter(Q(name__icontains = q.lower())|Q(name__startswith=q.lower())|Q(name__endswith=q.lower()))
            return render(request, 'core/productall.html',{"products":products,'q':q})
        else:
            products = Product.objects.all()
            return render(request, 'core/productall.html',{"products":products,'q':q})

# product one

def oneproduct(request, id):
    if request.method == "GET":
        product = get_object_or_404(Product, id=id)
        comt = Comment.objects.filter(product=product)
        if request.user.is_authenticated:
            user = request.user
            cart_ = Cart.objects.get(user = user)
            orderitems = OrtherItem.objects.filter(cart = cart_)
            count = orderitems.count()
            return render(request, 'core/productone.html',{'product':product,'count':count,'comt':comt})
        else:
            count = 0
            return render(request, 'core/productone.html',{'product':product,'count':count,'comt':comt})
    else:
        return redirect('core:index')
    


# cart

def cart__(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            user = request.user
            cart_ = get_object_or_404(Cart, user=user)
            if cart_:
                orderitems = OrtherItem.objects.filter(cart = cart_)
                count = orderitems.count()
                return render(request, 'core/cart.html',{'orderitems':orderitems,'cart':cart_,'count':count})
            else:
                return redirect('account:register')
        # delete Orderitem
        if request.method == "POST":
            id= request.POST.get("id")
            OrtherItem.objects.get(id=id).delete()
            return redirect('core:cart')
    else:
        return redirect('account:login')
    

# add orderitem

def addorderitem(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            user = request.user
            cart = get_object_or_404(Cart, user=user)
            id = request.POST.get('id')
            quantity = request.POST.get('quantity')
            product = get_object_or_404(Product, id=id)
            OrtherItem.objects.create(cart=cart, product=product,quantity=quantity)
            return redirect('core:cart')
    else:
        return redirect('account:login')
    

# delete orderitem
def edititem(request, id):
    if request.user.is_authenticated:
        if request.method == "GET":
            oderitem = get_object_or_404(OrtherItem, id=id)
            return render(request, 'core/edit.html',{'oderitem':oderitem})
        if request.method == "POST":
            quantity = request.POST.get('quantity')
            oderitem = get_object_or_404(OrtherItem, id=id)
            oderitem.quantity = quantity
            oderitem.save()
            return redirect('core:cart')
    else:
        return redirect('account:login')

# checkout
def checkout(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            user = request.user
            cart = Cart.objects.get(user=user)
            orderitems = OrtherItem.objects.filter(cart = cart)
            count = orderitems.count()
            return render(request, 'core/checkout.html',{'orderitems':orderitems,'cart':cart,'count':count})
        if request.method == "POST":
            name = request.POST.get('name')
            email = request.POST.get('email')
            number = request.POST.get('number')
            address = request.POST.get('address')
            if name != "" and email != "" and number != "" and address != ""  :
                user = request.user
                cart = Cart.objects.get(user=user)
                order = OrtherItem.objects.filter(cart=cart)
                if order:
                    description=""
                    total = 0
                    item = 0
                    for total_price in order:
                        description+=str(total_price.product.name)+" : $"+str(total_price.product.price)+" ,"
                        item+=total_price.quantity
                        total+=int(total_price.quantity)*int(total_price.product.price)
                    shippings=ShippingAddress.objects.create(user=user, cart=cart, total_items=item, total=total, description=description, email=email, 
                                            adderss=address, mobile=number, name=name)
                    for i in order:
                        id = i.product.pk
                        product = get_object_or_404(Product, id=id)
                        product.hasbeensell = product.hasbeensell +1
                        product.save()
                    order.delete()
                else:
                    return redirect('core:checkout')
                return redirect('core:pending')
            else:
                return redirect('core:checkout')
    else:
        return redirect('account:login')
        

# pending
def pending(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            shippings = ShippingAddress.objects.filter(user=request.user)
            user = request.user
            cart_ = Cart.objects.get(user = user)
            orderitems = OrtherItem.objects.filter(cart = cart_)
            count = orderitems.count()
            return render(request, 'core/pending.html',{'shippings':shippings,'count':count})
        if request.method == "POST":
            shippings = ShippingAddress.objects.get(id=request.POST.get('id'))
            if shippings.received == False:
                return redirect('core:pending')
            else:
                PurchaseHistory.objects.create(user=request.user, total_items=shippings.total_items, total=shippings.total,
                                description=shippings.description, adderss=shippings.adderss, email=shippings.email, mobile=shippings.mobile)
                shippings.delete()
                return redirect('core:pending')
    else:
        return redirect('account:login')
        

# profile

def profile(request):
    if request.user.is_authenticated:
        user = request.user
        customer = customeruser.objects.get(user=user)
        purchs = PurchaseHistory.objects.filter(user=user)
        cart_ = Cart.objects.get(user = user)
        orderitems = OrtherItem.objects.filter(cart = cart_)
        count = orderitems.count()
        return render(request, 'core/profile.html',{'user':user,'purchs':purchs,'count':count,'customer':customer})
    else:
        return redirect('account:login')
    

# comment
def comment_(request):
    if request.user.is_authenticated:
        id = request.POST.get('id')
        if request.POST.get('id') != "" and request.POST.get('number') !="" and request.POST.get('bl')!="":
            number_star = request.POST.get('number')
            cm = request.POST.get('bl')
            product = get_object_or_404(Product, id = id)
            user = request.user
            comt = Comment.objects.create(user =user, product=product, comment=cm, star=number_star)
            comt.save()
            count_ = Comment.objects.count()
            sao = (float(count_-1)*(product.evaluate)+float(number_star))/count_
            sao = round(sao, 2)
            product.evaluate = sao
            product.save()
            return redirect('core:oneproduct', id=id)
        else:
            return redirect('core:oneproduct', id=id)
    else:
        return redirect('account:login')


# contact
def contact(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            user = request.user
            cart_ = Cart.objects.get(user = user)
            orderitems = OrtherItem.objects.filter(cart = cart_)
            count = orderitems.count()
            return render(request, 'core/contact.html',{'count':count})
        else:
            return redirect('account:login')
    else:
        return redirect('core:index')
    
# updateprofile

def updateprofile(request):
    if request.user.is_authenticated:

product/views.py
from django.shortcuts import render

# Create your views here.

core/templates/core/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'core:search' %}" method="GET">
          <input class="form-control me-2" name="q" type="type" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
      {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Personal
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'core:profile' %}">Trang cá nhân</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:pending' %}">Đơn hàng</a></li>
                <li><hr class="dropdown-divider"></li>
              </ul>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cart' %}">Cart ({{count}})</a>
          </li>
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
          </li>
          {% else %}
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">Login</a>
          </li>
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Signup</a>
          </li>
    </ul>
    {% endif %}
    </div>
  </nav>
{% endblock header %}

{% block cart %}

<div class="container mt-5">
    <h1 class="mb-5">Cart</h1>
    <div class="row">
      <div class="col-md-8">
        <table class="table">
          <thead>
            <tr>
              <th scope="col" style="flex:1">Image</th>
              <th scope="col" style="flex:1">Product</th>
              <th scope="col" style="flex:1">Price</th>
              <th scope="col" style="flex:1">Quantity</th>
              <th scope="col" style="flex:1">Total</th>
              <th scope="col" style="flex:1">Edit</th>
            </tr>
          </thead>
          <tbody>
            {% for i in orderitems %}
            <tr>
              <td style="flex:1">
                <div style="width:50px">
                  <img src={{i.product.ImageURL}} style="width:80%"/>
                </div>
              </td>
              <td style="flex:1">{{i.product.name}}</td>
              <td style="flex:1">${{i.product.price}}</td>
              <td style="flex:1" >{{i.quantity}}</td>
              <td style="flex:1">${{i.total_price}}</td>
              <td style="flex:1">
                <button type="button" class="btn btn-primary btn-sm mb-2">
                  <a href="{% url 'core:edit' i.id %}" style="text-decoration: none;color:#fff;">Fix</a>
                  </button>
                  <form action="" method="post" >
                    {% csrf_token %}
                    <button type="submit" name='id' value="{{i.id}}" class="btn btn-danger btn-sm">
                      Delete
                    </button>
                  </form>
              </td>
            </tr> 
            {% endfor %}
          </tbody>
          
        </table>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">Summary</div>
          <div class="card-body">
            <table class="table">
              <tbody>
                <tr>
                  <td>Total</td>
                  <td>${{cart.total_items_price}}</td>
                </tr>
                <tr>
                    <td>Item</td>
                    <td>{{cart.total_item}}</td>
                </tr>
              </tbody>
            </table>
            <div>
              {% if orderitems %}
              <button type="button" class="btn btn-success">
                <a href="{% url 'core:checkout' %}" style="text-decoration: none;color:green;color:#fff">Checkout</a>
              </button>
              {% endif %}
            </div>
{% endblock cart %}

core/templates/core/productone.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Product{% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'core:search' %}" method="GET">
          <input class="form-control me-2" name="q" type="type" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
      {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Personal
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'core:profile' %}">Trang cá nhân</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:pending' %}">Đơn hàng</a></li>
                <li><hr class="dropdown-divider"></li>
              </ul>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cart' %}">Cart ({{count}})</a>
          </li>
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
          </li>
          {% else %}
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">Login</a>
          </li>
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Signup</a>
          </li>
    </ul>
    {% endif %}
    </div>
  </nav>
{% endblock header %}

{% block productone %}

<div class="container mt-5">
    <div class="row">
      <div class="col-lg-6">
        <img src="{{product.ImageURL}}" alt="Product Image" class="img-fluid">
      </div>
      <div class="col-lg-6">
        <h2>{{product.name}}</h2>
        <p>Lorem ipsum dsagittis justo congue non. Fusce condimentum ipsum ac lectus dapibus, vel bibendum elit convallis.</p>
        <h3>{{product.price}} VND</h3>
        <p>đã bán : {{product.hasbeensell}}</p>
        <p>Đánh giá : {{product.evaluate}} <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
          <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
        </svg></p>
        <form method="post" action="{% url 'core:addorderitem' %}">
          {% csrf_token %}
        <div class="buttons_added m-3">
            Số lượng: <input aria-label="quantity" class="input-qty" max="1000" min="1" name="quantity" type="number" value="1">
        </div>
        <button class="btn btn-primary" name="id" value="{{product.id}}">Add to Cart</button>
      </form>
      </div>
    </div>
</div>
{% endblock productone %}

{% block comment %}
<div class=" m-5">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h4 class="text-center mb-4">Product Review</h4>
      <form action="{% url 'core:commet' %}" method="post" class="mt-2">
        {% csrf_token %}
        <div class="form-group mb-2">
          Evaluate : <input aria-label="quantity" class="input-qty" max="5" min="0" name="number" type="number" value="0"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
          </svg>
        </div>
        <div class="form-group">
          <label for="comment">Your Comment</label>
          <textarea class="form-control mb-2" id="comment" name="bl" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary" name="id" value="{{product.id}}">Submit</button>
    </form>
      {% for cm in comt %}
      <div class="m-5">
        <div>User : {{cm.user.username}}</div>
        <div class="mt-3 mb-3">Evaluate :  {{cm.star}} <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
          <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
        </svg> </div>
        <div>Comment: {{cm.comment}} </div>
        <div>{{cm.created_at}} </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock comment %}

core/templates/core/profile.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Profile{% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'core:search' %}" method="GET">
          <input class="form-control me-2" name="q" type="type" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
      {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Personal
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'core:profile' %}">Trang cá nhân</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:pending' %}">Đơn hàng</a></li>
                <li><hr class="dropdown-divider"></li>
              </ul>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cart' %}">Cart ({{count}})</a>
          </li>
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
          </li>
          {% else %}
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">Login</a>
          </li>
          <li li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Signup</a>
          </li>
    </ul>
    {% endif %}
    </div>
  </nav>
{% endblock header %}

{% block trangcanhan %}
<div class="container mt-5">
  <h1 class="container mt-5 mb-5">Tìm kiếm trang cá nhân người lạ</h1>
  <form class="d-flex" role="search" action ="{% url 'chatapp:home' %}" method = "POST">
    {% csrf_token %} 
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
      <input class="form-control me-2 " type="search" placeholder="Search profile" name="name" aria-label="Search">
      <button class="btn btn-outline-success " type="submit">Search</button>

  </form>
</div>
<section class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2>Thông tin cá nhân</h2>
          <p>Họ và tên: {{customer.name}}</p>
          <p>Email: {{user.email}}</p>
          <p>Số điện thoại: {{customer.number_phone}}</p>
          <p>Địa chỉ: {{customer.address}}</p>
          <div><button class="btn-primary"><a href="{% url 'core:updateprofile' %}" style="color:#fff;text-decoration: none">Cập nhật tài khoảng</a></button></div>
          <div><button class="btn-warning mt-2"><a href="{% url 'account:doimatkhau' %}" style="color:#fff;text-decoration: none">Đổi mật khẩu</a></button></div>
        </div>
        <div class="col-md-6">
          <h2>Lịch sử mua hàng</h2>
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Các sản phẩm đã mua + Tiền</th>
                <th scope="col">Tổng sản phẩm</th>
                <th scope="col">Thành tiền</th>
                <th scope="col">Ngày mua</th>
              </tr>
            </thead>
            <tbody>
                {% for purch in purchs %}
              <tr>
                <td>{{purch.description}}</td>
                <td>{{purch.total_items}}</td>
                <td>${{purch.total}}</td>
                <td>{{purch.date_added|date:"d-m-Y"}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>


{% endblock trangcanhan %}