chatapp/urls.py
from django.urls import path
from .import views
app_name = 'chatapp'
urlpatterns = [
    path('getMessages/<int:id>/', views.getMessages, name='getMessages'),
    path('', views.home, name='home'),
    path('message/<int:id>', views.messa, name='message'),
    path('send/', views.send, name='send'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('account.urls')),
    path('chat/', include('chatapp.urls')),
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

chatapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    user_id1 = models.IntegerField()
    user_id2 = models.IntegerField()
    created_ed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)
    

class Messange(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    value = models.TextField()
    created_ed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

chatapp/views.py
from django.shortcuts import render
from django.contrib import messages
# Create your views here.
from django.shortcuts import render, HttpResponse, redirect
from .models import Messange,Room
from django.contrib.auth.models import User
from django.http import JsonResponse,HttpResponse
# Create your views here.
from django.http import HttpResponseBadRequest
def home(request):
    if request.method == "GET":
        return redirect('core:profile')
    if request.method == "POST":
        name = request.POST.get('name')
        if name!="":
            try:
                user_ = User.objects.get(username = name)
            except User.DoesNotExist:
                messages.success(request, "Tài khoảng không tồn tại")
                return redirect('chatapp:home')
            return render(request, 'chat/profile.html',{'user_':user_})
        else:
            messages.success(request, "bạn cần nhập tên tài khoảng bạn muốn tìm kiếm")
            return redirect('chatapp:home')
    
def messa(request,id):
    if request.method == "GET":
        user = request.user
        id2 = request.user.pk
        try:
            room = Room.objects.get(user_id1=id, user_id2=id2)
        except Room.DoesNotExist:
            try:
                room = Room.objects.get(user_id1=id2, user_id2=id)
            except Room.DoesNotExist:
                room = Room.objects.create(user_id1=id2, user_id2=id)
        try:
            mess = Messange.objects.filter(room=room)
            return render(request, 'chat/message.html', {'messages': mess,'room':room,'user':user})
        except Messange.DoesNotExist:
            mess = []
        return render(request, 'chat/message.html', {'messages': mess,'room':room,'user':user})



def send(request):
    username = request.user
    room_id = request.POST.get('room_id')
    message = request.POST.get('message')
    if room_id:
        room_id = int(room_id)
        # Retrieve the Room instance using the room_id string
        try:
            room = Room.objects.get(id=room_id)
        except Room.DoesNotExist:
            return HttpResponseBadRequest("Invalid room ID")
        if message!="":
            # Create the new message using the retrieved Room instance
            new_mess = Messange.objects.create(value=message, room=room, user=username)
            new_mess.save()
        else:
            return redirect('chapapp:message', id=room_id)
        
        return HttpResponse("Message sent successfully")
    
    # Add a default return statement
    return HttpResponseBadRequest("Invalid request")


def getMessages(request, id):
  
    room_details = Room.objects.get(id=id)
    username =[]
    messages = Messange.objects.filter(room=room_details)
    for i in messages:
        username.append(i.user.username)
    return JsonResponse({"messages":list(messages.values()),"user":username})

chatapp/templates/chat/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <style>
            .container {
                border: 2px solid #dedede;
                background-color: #f1f1f1;
                border-radius: 5px;
                padding: 10px;
                margin: 10px 0;
              }
              
              .darker {
                border-color: #ccc;
                background-color: #ddd;
              }
              
              .container::after {
                content: "";
                clear: both;
                display: table;
              }
              
              .container img {
                float: left;
                max-width: 60px;
                width: 100%;
                margin-right: 20px;
                border-radius: 50%;
              }
              
              .container img.right {
                float: right;
                margin-left: 20px;
                margin-right:0;
              }
              
              .time-right {
                float: right;
                color: #aaa;
              }
              
              .time-left {
                float: left;
                color: #999;
              }
        </style>
    </head>
    <body>
       

        {% block profile %}{% endblock profile %}
        {% block search %}{% endblock search %}
        {% block content %}{% endblock content %}


        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </body>
</html>

chatapp/templates/chat/home.html
{% extends 'chat/base.html' %}

{% block search %}

<div class="container mt-5">
    <h1 class="container mt-5 mb-5">Tìm kiếm trang cá nhân</h1>
    <form class="d-flex" role="search" action ="" method = "post">
        {% csrf_token %} 
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
        <input class="form-control me-2" type="search" placeholder="Search" name="name" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</div>
{% endblock search %}

chatapp/templates/chat/message.html
{% extends 'chat/base.html' %}

{% block content %}
    
  <div class="container mt-4">
    <div class="message">
        <h2>{{room}} - DjChat</h2>

        <div id="display">
        
        <!-- <div class="container darker">
          <b>Tom</b><p>Hello Everyone, How Are You Guys Doing?</p>
          <span class="time-left">20th, April 2021</span>
        </div> -->
        </div>
        
        <script>
            $(document).ready(function(){
                
                setInterval(function(){
                    $.ajax({
                        type: 'GET',
                        url: "{% url 'chatapp:getMessages' id=room %}",
                        success: function(response){
                            $("#display").empty();
                            console.log(response)
                            for (var key in response.messages)
                            {
                                var temp="<div class='container darker'><b>"+response.user[key]+"</b><p>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                                $("#display").append(temp);
                            }
                        },
                        error: function(response){
                           // alert('An error occured')
                        }
                    });
                },1000);
            });
        </script>

        <div class="container">
    <form  id="post-form">
        {% csrf_token %}
        <div class="form-group">
            <input type="hidden" name="username" id="username" value="{{user}}"/>
            <input type="hidden" name="room_id" id="room_id" value="{{room.id}}"/>
            <textarea class="form-control" id="message"  name="message" rows="3" placeholder="Type your message here"></textarea>
        </div>
        <button type="submit" class="submit">Send</button>
      </form>
    </div>
  </div>
  
<script>
    $(document).on('submit','#post-form',function(e){
        e.preventDefault();
        var roomId = parseInt($('#room_id').val());
        if (isNaN(roomId)) {
          alert('Invalid room ID');
          return;
        }
        $.ajax({
          type:'POST',
          url:'{% url 'chatapp:send' %}',
          data:{
              username:$('#username').val(),
              room_id: roomId,
              message:$('#message').val(),
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
          },
          success: function(data){
           // alert(data)
          }
        });
        document.getElementById('message').value = ''
      });

</script>
{% endblock %}

chatapp/templates/chat/profile.html
{% extends 'chat/base.html' %}

{% block profile %}
<div class="container mt-4">
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ user_.username }}</h5>
            <p class="card-text">{{ user_.email }}</p>
            <p class="card-text">{{ user_.date_joined }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <form action="{% url 'chatapp:message' user_.pk %}" method="get">
          {% csrf_token %}
        <button type="submit" name="id" value = "{{user_.pk}}" class="btn-primary">nhắn tin</button>
      </form>
      </div>
    </div>
  </div>

{% endblock profile %}